const serverURLS = {
  LOGIN: '/auth/login',
  REGISTRATION: '/auth/registration',
  ACTIVATION: '/auth/activation',
  BOOKING_LIST: '/admin/getBookings',
  ROOMS_LIST: '/admin/get-rooms',
  REPORTS_LIST: '/admin/get-reports',
  GET_PET: '/admin/get-pet',
  GET_CAMPS: '/client/petCamps',
  GET_FREE_ROOMS: '/client/freeRooms',
  GET_BOOKING_SECTION: '/client/clientProfileInfo',
  GET_PETS: '/client/pets',
  ADD_PET: '/client/pets',
  ADD_BOOKING: '/client/bookings',
  GET_MY_SETTINGS: 'client/mySettings',
  ADD_SETTINGS: 'client/mySettings',
  DELETE_PET: 'client/delete-pet',
  DELETE_BOOKING: 'client/delete-booking',
  DISABLE_BOOKIGN: 'client/disable-booking',
  ADMIN_DISABLE_BOOKIGN: 'admin/disable-booking',
  GET_BOOKINGS: 'client/bookings',
  GET_CALENDAR: 'client/get-calendar',
  ADD_REPORT: '/admin/post-report',
  GET_REPORTS_NUMBER: '/admin/get-reports-number',
  GET_REPORTS: '/client/reports',
  FORGOT_PASSWORD: '/client/forgot-password',
  CHANGE_PASSWORD: '/client/change-password',
};

export default serverURLS;
